CREATE TABLE contact_log (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    lover VARCHAR(50) NOT NULL,
    contact_date DATE NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);